export enum ModulesConstants {
  WRITE_KEYLOOP = 'WRITE_KEYLOOP',
  ADVANCED_SEARCH = 'ADVANCED_SEARCH',
  SMS_SEND = 'SMS_SEND',
  WHATSAPP_SEND = 'WHATSAPP_SEND',
  CHECK_LIST = 'CHECK_LIST',
  ACCOUNTING = 'ACCOUNTING',
  CARD_LIMIT = 'CARD_LIMIT'
}
