export enum ModulesConstants {
  WRITE_KEYLOOP = 'WRITE_KEYLOOP',
  ADVANCED_SEARCH = 'ADVANCED_SEARCH',
  SMS_SEND = 'SEND_SMS',
  WHATSAPP_SEND = 'SEND_WHATSAPP',
  CHECK_LIST = 'CHECK_LIST',
  ACCOUNTING = 'ACCOUNTING',
  CARD_LIMIT = 'CARD_LIMIT',
  TIME_LINE = 'TIME_LIME',
  BUDGET = 'BUDGET',
  TPV = 'TPV',
  PAYMENTS = 'PAYMENTS'
}
